fun main(args: Array<String>) {
    val Fisica = Fisica ()


    println("Digite a Massa:")
    val massa: Float = readLine()!!.toFloat()
    println("Digite a Gravidade:")
    val gravidade: Float = readLine()!!.toFloat()
   println("Digite a Velocidade:" )
    val velocidade:Float = readLine()!!.toFloat()
   println("Digite o Raio Da Curva:")
    val curva:Float = readLine()!!.toFloat()
   println("Digite a Forca Newton:")
    val forcaNewton:Float = readLine()!!.toFloat()
    println("Digite o Tempo Final:")
    val tempoFinal:Float = readLine()!!.toFloat()
    println("Digite o Deslocamento Em Metros:")
    val deslocamentoEmMetros:Float = readLine()!!.toFloat()
   println("Digite o Deslocamento?")
    val deslocamento:Float = readLine()!!.toFloat()
   println("Digite o Intervalo De Tempo:")
    val intervaloDeTempo:Float = readLine()!!.toFloat()
   println("Digite o Espaco Inicial:")
    val espacoInicial:Float = readLine()!!.toFloat()
    println("Digite o Tempo:")
    val tempo:Float = readLine()!!.toFloat()
   println("Digite o Tempo Inicial:")
    val tempoInicial:Float = readLine()!!.toFloat()
   println("Digite a Aceleração:")
    val aceleracao:Float = readLine()!!.toFloat()
   println("Digite a Velocidade Inicial:")
    val velocidadeInicial:Float = readLine()!!.toFloat()
   println("Digite o Velocidade Final:")
    val velocidadeFinal = readLine()!!.toFloat()

    val calcularForcaPeso = Fisica.calcularForcaPeso(massa,gravidade)
    val calcularForcaCentripeta = Fisica.calcularForcaCentripeta(massa,velocidade,curva)
    val calcularImpulso = Fisica.calcularImpulso(forcaNewton,tempoFinal,tempoInicial)
    val calcularForcaElastica = Fisica.calcularForcaElastica(forcaNewton,deslocamentoEmMetros)
    val calcularVelocidadeMedia = Fisica.calcularVelocidadeMedia(velocidadeInicial,velocidadeFinal,tempoInicial,tempoFinal)
    val calcularMru = Fisica.calcularMru(velocidade,tempo,espacoInicial,tempoFinal)
    val calcularMruv = Fisica.calcularMruv(espacoInicial,tempo,aceleracao,velocidadeInicial)

    println("O resultado da Forca Peso é $calcularForcaPeso")
    println("O resultado da Forca Centripeta é $calcularForcaCentripeta")
    println("O resultado do Impulso é $calcularImpulso")
    println("O resultado da Forca Elastica é $calcularForcaElastica")
    println("O resultado da Velocidade Média é $calcularVelocidadeMedia")
    println("O resultado da Mru é $calcularMru")
    println("O resultado da calMruv é $calcularMruv")
}